
apiVersion: v1
kind: Service
metadata:
  name: wso2ei-integrator-gateway-service
  namespace: "$ns.k8s&wso2.ei"
  labels:
    deployment: wso2ei-integrator
    product: wso2ei
spec:
  selector:
    deployment: wso2ei-integrator
    product: wso2ei
  type: NodePort
  ports:
    - name: pass-through-http
      port: 8280
      targetPort: 8280
      protocol: TCP
    - name: pass-through-https
      port: 8243
      targetPort: 8243
      protocol: TCP
      nodePort: "$nodeport.k8s.&.2.wso2ei"
---
