
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2ei-with-analytics-integrator-deployment
  namespace: wso2
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      deployment: wso2ei-integrator
      product: wso2ei
  template:
    metadata:
      labels:
        deployment: wso2ei-integrator
        product: wso2ei
    spec:
      containers:
        - name: wso2ei-integrator
          image: wso2/wso2ei-integrator:6.5.0
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - nc -z localhost 9443
            initialDelaySeconds: 60
            periodSeconds: 10
          imagePullPolicy: Always
          ports:
            - containerPort: 8280
              protocol: TCP
            - containerPort: 8243
              protocol: TCP
            - containerPort: 9763
              protocol: TCP
            - containerPort: 9443
              protocol: TCP
---
