
apiVersion: v1
kind: Service
metadata:
  name: wso2ei-with-analytics-worker-service
  namespace: "$ns.k8s&wso2.ei"
spec:
  selector:
    deployment: wso2ei-with-analytics-worker
    product: wso2ei
  ports:
    - name: data-receiver-2
      port: 7612
      targetPort: 7612
      protocol: TCP
    - name: http-default
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: siddhi-defaul
      port: 7070
      targetPort: 8082
      protocol: TCP
    - name: siddhi-msf4j-https
      port: 7443
      targetPort: 11501
      protocol: TCP
    - name: data-receiver-1
      port: 7712
      targetPort: 7712
      protocol: TCP
    - name: http-msf4j-https
      port: 9444
      targetPort: 9444
      protocol: TCP
    - name: data-receiver-binary-1
      port: 9711
      targetPort: 9711
      protocol: TCP
    - name: data-receiver-binary-2
      port: 9611
      targetPort: 9611
      protocol: TCP
---
